"""initial tables

Revision ID: 410c9f42f685
Revises: 9c509b39a5d1
Create Date: 2026-09-02 14:10:16.287382
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '410c9f42f685'
down_revision: Union[str, None] = '9c509b39a5d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
